### ISSUE TITLE
Email subject contains the entire message

### ISSUE THREAD

**Issue by DanTulovsky** [notify-events/notify-events#9]
Hi,

When sending an email notification (generated by Home Assistant like this:

```
alias: Send notification
action: notify.events
data:
  target: null
  title: '{{ now().strftime(''%A'') }} Agenda'
  message: '{{ agent.response.speech.plain.speech }}'
```

the title seems to be ignored and the email Subject line contains the entire message instead.
